### ISSUE TITLE
项目发布

### ISSUE THREAD

**Issue by gyh9457** [gem-mine/glaucus#14]
1. 目前暂定只发一个 `rc-slate-component` ，是否将其他的包的 package.json 删除，直接通过文件引入？
2. `rc-slate-component` 的构建产物需要支持 es cjs umd. fish 会以 umd 的形式引入。
3. 是否改个名字？起名太头疼了
4. gem-mine/salte 先发一个 0.0.1 版本 解决中文重复输入问题？

**Comment by githoniel** [comment]
1. 只发主包，但是目前根据包进行结构分离的方式不变。
monorepo最重要的是一种组织代码的方式，发布只是他的一部分功能，我认为维持目前的分包结构有利于后期继续迭代
2. 这个没问题，component模板支持cjs/umd, es不支持也没关系
3. 名字已改，见现名
4. slate已经整体合并
