### ISSUE TITLE
`toobar`按钮的可用性判定

### ISSUE THREAD

**Issue by githoniel** [gem-mine/glaucus#15]
# 场景

很多时候，某些选区下不能执行某些操作，需要将按钮值为`disable`。

- 当前表格尚不能很好的支持图片，于是表格想禁止插入图片
- 文字类Mark，不应当对图片生效
- HR目前是全幅的，不应当支持左右对齐

# 机制分析

1. `Selection`变化会引起`toolbar`重新渲染
2. `toolbar`可以实时获取`selection`值

所以问题等价于如何判定当前`point`下，能否执行某些操作的问题。

# 实现方式

## 特殊key

通过插件提供特殊Key的方式阻止特定操作。

比如`Image`类提供特殊`disable-key = 'not-allow-image'`，Table组件渲染时候，必须给`TableCell`的`schema`上添加属性`not-allow-image`。

```
interface TableCell {
   typpe: 'table-cell',
   'not-allow-image': any
}
```

`Image`按钮渲染时，`point`的`parentElement`存在`key: not-allow-image`，则按钮`disable`

## type过滤

通过插件自己过滤`element.type`判定是否可以执行某些操作。

比如`Image`按钮渲染时，判定当前`point`的`parentElement.type`，不符合条件则`disable`

# 对比

两个方法的最大差异在于谁负责实现。

`特殊key`的机制，Image判定自己是否能够插入Table，根源来自Table组件，也就是以后开发新的X组件，这个X组件能否插入图片，由X自己负责判断，X改代码就行。

`type`过滤就是相反，能否插入的判断是Image，以后新增X组件，X能否插入图片，是由Image来判断，这个就有点奇怪。假如X是一个复杂的表单组件，有些地方可以插入图片有些又不可以，逻辑复杂情况下Image会写入大量与自身无关的代码。

**Comment by githoniel** [comment]
- [] mark插件改造
  - [] getBaseIcon改造
  - [] active状态判定

**Comment by githoniel** [comment]
目前这个`特殊key`也有严重缺陷，判断值是存储在schema中，而不是运行时, 所以需要更好的办法。

难道又要上蛋疼的MirrorNode？

**Comment by githoniel** [comment]
本质是要找到一个Node的载体，来承载函数和一些运行态的值。 目前发现可以利用DomNode。

`slate`自身提供了函数方便的进行转换

1. 从当前Range获取DomNode: 根据`selection`取得`node`后，`ReactEditor.toDOMNode(editor: ReactEditor, node: Node)`获得DomNode
2. Render时候获取DomNode: Attribute.ref就是一个当前DomNode的引用, useEffect里取得即可

**Comment by gyh9457** [comment]
不可用的 button 是否隐藏？

**Comment by githoniel** [comment]
需要hide么，目前是设计3种状态

1. 可用 - 普通Button
2. 当前已激活 - hover
3. 当前不可用 - 灰色

**Comment by gyh9457** [comment]
首次渲染不可用状态异常，待排查

**Comment by githoniel** [comment]
首次渲染不可用，是因为React渲染时序问题，由于toolbar需要访问Editable的DOM结果，但是react render都结束后，才执行commit phase

现在采用Editable committed后，强制刷新一次toolbar来解决
